### ISSUE TITLE
Failures and botched up video output on multiple monitor setup

### ISSUE THREAD

**Issue by nk521** [kirides/go-d3d#6]
I have 2 monitors in extended mode.
1. 2560 x 1440 px
2. 1920 x 1080 px

Context: I'm running the [mjpegstream example](https://github.com/kirides/go-d3d/tree/main/examples/mjpegstream)

If I just use any one of these then its fine but the program just fails when I have both connected and I try to record from the primary (index 0) monitor! This is the failure output - 

```
Registering stream 0
Registering stream 1
Enabled PerMonitorAwareV2 DPI awareness.
Enabled PerMonitorAwareV2 DPI awareness.
panic: runtime error: slice bounds out of range [8304640:8294400]

goroutine 8 [running, locked to thread]:
github.com/kirides/go-d3d/outputduplication.(*OutputDuplicator).GetImage(0xc000132000, 0xc00007e280, 0x10afca0?)
        C:/Users/.../go/pkg/mod/github.com/kirides/go-d3d@v1.0.1-0.20230623183646-afb04af36898/outputduplication/output_duplication.go:253 +0x25e
main.streamDisplayDXGI({0x10b1fe8, 0xc00007e240}, 0x0, 0x19, 0x0?)
        I:/code/...go:157 +0x579
created by main.main in goroutine 1
        I:/code/...go:63 +0x2d1
exit status 2
```

But on non-primary monitor I get output like this - 

![image](https://github.com/kirides/go-d3d/assets/30789322/a94ec5cb-a65e-4cbe-8c8d-968374790c7e)

The error occurs here -> https://github.com/kirides/go-d3d/blob/afb04af3689873e4548c205d89026a26b0524efb/outputduplication/output_duplication.go#L253

**Comment by Tecnology73** [comment]
I had this issue when using 3440x1440 & 2560x1440 monitors. For me, I could capture the 2560 monitor just fine but it was distorted (similar to your image) when capturing the 3440 monitor.

After searching for hours and trying random image sizes, I found that the 3440 capture worked if I used an image size of 3456x1440 (16 pixels wider than the actual resolution). I couldn't find any reason why this worked (and I don't know anything about this API) so I asked ChatGippity and it responded with this:

> The Desktop Duplication API requires the pitch (the number of bytes in a row of the image) to be aligned to a specific boundary, usually 256 bytes. When the width of your output image (in pixels) is not a multiple of the required alignment, the image may become warped.

The solution (that it also provided) was to use this to "align the width":
```cpp
int alignedWidth = ((width * 4 + 255) & ~255) / 4;
```

**Comment by kirides** [comment]
This is interesting, as GetImage already uses aligned reads on the Pitch

```go
contentWidth := int(size.X) * 4
dataWidth := int(mappedRect.Pitch)

var imgStart, dataStart, dataEnd int
// copy source bytes into image.RGBA.Pix, skipping padding
for i := 0; i < int(size.Y); i++ {
	dataEnd = dataStart + contentWidth
	copy(img.Pix[imgStart:], data[dataStart:dataEnd])
	imgStart += contentWidth // increase row-offset by actual width
	dataStart += dataWidth // move by Pitch (aligned width)
}
```

**Comment by kirides** [comment]
Oh, i see now. The issue is (most likely) that in cases where multiple different sized monitors are attached, the image gets the "virtual" display-size instead of the actual monitor resolution assigned.

`screenshot.GetDisplayBounds` returns the largest of all monitor sizes (Virtual size, as if all screens were a single wide screen)


EDIT: I need to correct this:
The library i used in the examples has different "order" for Display-indices, which breaks stuff.

i will update the examples to include code that actually uses the same output-index as the actual DXGI Output.

`screenshot.GetDisplayBounds(index)` is not the same as an `dxgiAdapter.EnumOutputs(index, ...)`
latter is what the examples SHOULD use to get correct bounds.

**Comment by nk521** [comment]
> Oh, i see now. The issue is (most likely) that in cases where multiple different sized monitors are attached, the image gets the "virtual" display-size instead of the actual monitor resolution assigned.

I never updated this here but afair, this is what that happened. If I hardcode the resolution and display index in your library then things used to work normally.

I'm happy that you figured the issue.

**Comment by kirides** [comment]
@nk521 would you mind checking if the examples now work for you?

While i was at it, i may have also reduced the amount of needless buffer updates and bounds checks in the example(s)
